name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      # ✅ Build Docker Image
      - name: Build Docker image
        run: docker build -t ash1185/ci-cd-github:latest .

      # ✅ Log in to Docker Hub (uses your secret)
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "ash1185" --password-stdin

      # ✅ Push image to Docker Hub w
      - name: Push image to Docker Hub
        run: docker push ash1185/ci-cd-github:latest
